"""add_spans_table

Revision ID: 3b9acc8c9e6c
Revises: d8ef9e277c02
Create Date: 2026-06-16 14:04:09.783590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b9acc8c9e6c'
down_revision: Union[str, Sequence[str], None] = 'd8ef9e277c02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('span_id', sa.String(length=32), nullable=False),
    sa.Column('parent_span_id', sa.String(length=32), nullable=True),
    sa.Column('trace_request_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('span_type', sa.String(length=30), nullable=False),
    sa.Column('input', sa.Text(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('tool_name', sa.String(length=255), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('status_code', sa.String(length=10), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=6), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spans_parent_span_id'), 'spans', ['parent_span_id'], unique=False)
    op.create_index(op.f('ix_spans_span_id'), 'spans', ['span_id'], unique=True)
    op.create_index(op.f('ix_spans_trace_id'), 'spans', ['trace_id'], unique=False)
    op.create_index(op.f('ix_spans_trace_request_id'), 'spans', ['trace_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spans_trace_request_id'), table_name='spans')
    op.drop_index(op.f('ix_spans_trace_id'), table_name='spans')
    op.drop_index(op.f('ix_spans_span_id'), table_name='spans')
    op.drop_index(op.f('ix_spans_parent_span_id'), table_name='spans')
    op.drop_table('spans')
    # ### end Alembic commands ###
